### ISSUE TITLE
How does this project be compatible with BPE tokenizers?

### ISSUE THREAD

**Issue by onebula** [rizerphe/local-llm-function-calling#13]
Hi, I have found this part in the doc:
<img width="1274" alt="image" src="https://github.com/rizerphe/local-llm-function-calling/assets/26182287/dd801184-8d45-4ca2-a5a6-6ddcb11d9cee">

It demonstrates the word "date" is not acceptable. Will sub workds like "uni" in BPE tokenizers are acceptable?

**Comment by rizerphe** [comment]
Thank you! Yes, the key doesn't have to be one token, not at all; a key constructed of several subword tokens will work just fine, this project is built around BPE tokenizers.
