### ISSUE TITLE
Could not install via pip 

### ISSUE THREAD

**Issue by bartanderson** [rizerphe/local-llm-function-calling#4]
I tried with python version 3.11.4 and it claimed that it was not between 3.11 and 4.0. I am on windows
I tried using the example locally and started loading the requirements and got to typing and it could not import NotRequired (I think it was in prompter) from typing but found it in typing_extensions. Seems like python is a mess between versions sometimes. It look like you are in the middle of making changes and that is why it can't be installed right now. Just wanted to give you a heads up. I am real interesting in trying this out.

**Comment by rizerphe** [comment]
I was able to successfully install this library and run the huggingface example from the quickstart in a fresh Windows 11 virtual machine running python 3.11.4, pip 23.1.2. Can you provide more details about your setup? Do `python -V` and `pip -V` return what you expect them to? `NotRequired` was only moved from typing_extensions into typing very recently, are you sure you only have one version of python installed on your machine or are running the correct version otherwise?

**Comment by bartanderson** [comment]
Sorry, I don't know why pyenv isn't bein honored, I use it to switch
environments and have many separate ones.
when I checked with python -V and pip -V I got 3.10.11 and 3.10
respectively. As you can see below, that's not what I configured, sorry to
have bothered you. I still don't know why there is this kind of difference.
Maybe it's just windows weirdness.

(local_llm_fc) D:\Github\local_llm_fc>pyenv versions
  3.10.10
  3.10.11
* 3.11.4 (set by D:\Github\local_llm_fc\.python-version)
  3.12.0a1
  3.8.10
  3.9.12

(local_llm_fc) D:\Github\local_llm_fc>pyenv local
3.11.4

(local_llm_fc) D:\Github\local_llm_fc>pyenv global
3.11.4

(local_llm_fc) D:\Github\local_llm_fc>pip install local-llm-function-calling
ERROR: Ignored the following versions that require a different python
version: 0.1.0 Requires-Python >=3.11,<4.0; 0.1.1 Requires-Python
>=3.11,<4.0; 0.1.10 Requires-Python >=3.11,<4.0; 0.1.11 Requires-Python
>=3.11,<4.0; 0.1.2 Requires-Python >=3.11,<4.0; 0.1.3 Requires-Python
>=3.11,<4.0; 0.1.4 Requires-Python >=3.11,<4.0; 0.1.5 Requires-Python
>=3.11,<4.0; 0.1.6 Requires-Python >=3.11,<4.0; 0.1.7 Requires-Python
>=3.11,<4.0; 0.1.8 Requires-Python >=3.11,<4.0; 0.1.9 Requires-Python
>=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement
local-llm-function-calling (from versions: none)
ERROR: No matching distribution found for local-llm-function-calling

(local_llm_fc) D:\Github\local_llm_fc>
