### ISSUE TITLE
Docs example doesn't seem correct

### ISSUE THREAD

**Issue by this-josh** [rizerphe/local-llm-function-calling#6]
Apologies as I am new to this package, but going through the docs the examples don't seem correct:

https://github.com/rizerphe/local-llm-function-calling/blob/d862388debb783aefe172d21146dfea26fd5ffe2/docs/generation.md?plain=1#L65

Note the schema is 
```python
functions = [
    {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                    "maxLength": 20,
                },
                "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
            },
            "required": ["location"],
        },
    }
]
```

When I run on `llama-2-7b-chat.Q5_K_M.gguf` I get 
```python 
>>> generator.generate("What is the weather like today in Brooklyn?")
{'name': 'get_current_weather', 'parameters': '{\n    "location": "type"\n}'}
```
which again doesn't provide an answer to the question but is slightly similar to the example.

**Comment by Nuclear6** [comment]
<img width="814" alt="image" src="https://github.com/rizerphe/local-llm-function-calling/assets/49468241/258e1550-a250-41e3-ace4-9282ae4942fd">

I also encountered similar problems

**Comment by rizerphe** [comment]
Thank you! This seems to be because of the token duplicated issue, I just fixed it, closing this for now. If it still doesn't work, feel free to re-open the issue.
