### ISSUE TITLE
Error at installing 

### ISSUE THREAD

**Issue by dabhadepratik1** [rizerphe/local-llm-function-calling#7]
using :- pip install local-llm-function-calling[llama-cpp]
 got following error:-
ERROR: Failed building wheel for llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
![Uploading function_calling.png…]()

**Comment by rizerphe** [comment]
This seems to be an issue with llama-cpp-python. Could not replicate. Closing for now.
